{
  "siteTitle": "Jerome Delos Reyes",
  "headerTitle": "Jerome Delos Reyes",
  "backgroundImage": "https://https://www.pexels.com/video/outer-space-856309/",
  "welcomeMessage": "Welcome to My EDM Tasks Portfolio 💾",
  "welcomeDescription": "This portfolio contains all of my documents in EDM.",
  "about": {
    "name": "Jerome Delos Reyes",
    "bio": "I am Jerome Delos Reyes, currently studying at City College of Angeles, taking Bachelor of Science in Information System.",
    "image": "https://github.com/user-attachments/assets/dff3da4f-90cd-4ad0-bd46-f4876ae9b835"
  },
  "education": {
    "college": "City College of Angeles",
    "highSchool": "Eastern Porac National High School",
    "elementary": "Manibaug Libutad Elementary School"
  },
  "midtermProjects": [
    {
      "title": "Midterm Lab Task 1: Data Cleaning and Preparation using EXCEL",
      "link": "#"
    },
    {
      "title": "Midterm Lab Task 2: Data Cleaning and Preparation using Power Query",
      "link": "#"
    },
    {
      "title": "Midterm Lab Task 3: Creating PIVOT TABLE and DASHBOARD",
      "link": "#"
    }
  ],
  "finalProjects": [
    {
      "title": "Finals Lab Task 1: Excel Data Cleaning",
      "link": "#"
    },
    {
      "title": "Finals Lab Task 2: Power Query",
      "link": "#"
    },
    {
      "title": "Finals Lab Task 3: Dashboarding",
      "link": "#"
    }
  ],
  "contact": {
    "email": "jrecapor24-0115@cca.edu.ph"
  },
  "footer": "© 2025 Jerome Delos Reyes. All rights reserved."
}
