{
  "portfolio": {
    "name": "Jerome Delos Reyes",
    "email": "jdelosreyes24-0115@cca.edu.ph",
    "github": "https://github.com/jdelosreyes/EDM-Jerome",
    "hero_image": "https://avatars.githubusercontent.com/u/202104250?s=400&u=efcd89ee1a19a0ecaf70a1c4fbb654a45a48c358&v=4",
    "about": {
      "bio": "I am Jerome Delos Reyes, currently studying at City College of Angeles with a course in Bachelor of Science in Information System. I am also currently working at Jollibee Cutcut Friendship."
    },
    "projects": {
      "midterm": [
        {
          "title": "Midterm Lab Task 1: Data Cleaning and Preparation using EXCEL",
          "url": "https://github.com/JDelosReyes27/Nunoypogi123/tree/main/Midterm%20Task%201"
        },
        {
          "title": "Midterm Lab Task 2: Data Cleaning and Preparation using Power Query",
          "url": "https://github.com/JDelosReyes27/Nunoypogi123/tree/main/Midterm%20Task%202"
        },
        {
          "title": "Midterm Lab Task 3: Creating PIVOT TABLE and DASHBOARD",
          "url": "https://github.com/JDelosReyes27/Nunoypogi123/tree/main/Midterm%20task%203"
        }
      ],
      "finals": [
        {
          "title": "Finals Lab Task 1:: Data Cleaning and Preparation using EXCEL",
          "url": "https://github.com/jdelosreyes/EDM-Jerome/tree/main/Final%20Task%201"
        },
        {
          "title": "Finals Lab Task 2: Data Cleaning and Preparation using Power Query",
          "url": "https://github.com/jdelosreyes/EDM-Jerome/tree/main/Final%20Task%202"
        },
        {
          "title": "Finals Lab Task 3: Creating PIVOT TABLE and DASHBOARD",
          "url": "https://github.com/jdelosreyes/EDM-Jerome/tree/main/Final%20Task%203"
        },
        {
          "title": "Finals Lab Task 5: Creating PIVOT TABLE and DASHBOARD",
          "url": "https://github.com/jdelosreyes/EDM-Jerome/tree/main/Final%20Task%205"
        }
      ]
    }
  }
}
