{
  "siteTitle": "Jerome Delos Reyes Portfolio",
  "backgroundImage": "assets/backrooms.jpg",
  "author": "Jerome Delos Reyes",
  "theme": {
    "textColor": "white",
    "font": "Arial, sans-serif"
  },
  "credit": {
    "name": "dalay-lamma",
    "url": "https://www.deviantart.com/dalay-lamma/art/The-Backrooms-wallpaper-seamless-909255587"
  }
}
